== Application

The application layer is responsible for driving the workflow of the 
application, matching the business use cases at hand. These operations are 
interface-independent and can be both synchronous or asynchronous. This layer 
is well suited for spanning transactions, high-level logging, and security.

Note, the application layer is very thin in terms of domain logic - it merely 
coordinates the domain layer objects to perform the actual work. This is very 
different from traditional tiered architectures that tend to look more 
procedural with a lot of business logic in the application layer.

The 
https://github.com/eclipse-ee4j/cargotracker/tree/master/src/main/java/org/eclipse/cargotracker/application[org.eclipse.cargotracker.application] 
package contains all the application classes. The application layer is 
typically implemented using Enterprise Beans (EJB) or CDI beans. Other 
Jakarta EE APIs likely to be used in this layer are Jakarta Security, 
Transactions (JTA), Concurrency, and Interceptors.
