package org.eclipse.cargotracker.domain.model.cargo;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import jakarta.validation.constraints.NotEmpty;
import java.io.Serializable;
import java.util.Objects;

/** Uniquely identifies a particular cargo. Automatically generated by the application. */
@Embeddable
public record TrackingId(
    @Column(name = "tracking_id", unique = true, updatable = false)
        @NotEmpty(message = "Tracking ID cannot be empty.")
        String id)
    implements Serializable {

  public TrackingId {
    Objects.requireNonNull(id);
  }

  @Override
  public String toString() {
    return id;
  }
}
